### ISSUE TITLE
backuppuller user has files `config` and `known_hosts` that belong to root

### ISSUE THREAD

**Issue by carygravel** [Yannik/ansible-role-rsnapshot-backup-host#4]
backuppuller user has files `config` and `known_hosts` that belong to root. Therefore, the user has no permission for them and ssh fails.

Once I had `chown`ed and `chgrp`ed them back to backuppuller, ssh worked.

**Comment by carygravel** [comment]
Thanks for the update. I'm an ansible newbie. Is there an automatic method of updating the version of your code that I installed from ansible-galaxy with the source in this repo so that I can test your changes?

**Comment by Yannik** [comment]
I suggest you use the following in your `requirements.yml`:

```
 - name: yannik.rsnapshot-backup-host
   src: https://github.com/Yannik/ansible-role-rsnapshot-backup-host.git
```

Then you can simply `ansible-galaxy role install --force`.

**Comment by carygravel** [comment]
Thanks. Confirmed your fix.
